-- Baseado em scripts/bd_ferroVelho.sql (SQL Server) e convertido para PostgreSQL.
-- Execucao:
--   psql -U postgres -f scripts/create_bd_ferrovelho_postgres.sql

SELECT 'CREATE DATABASE bd_ferrovelho'
WHERE NOT EXISTS (
  SELECT 1 FROM pg_database WHERE datname = 'bd_ferrovelho'
)\gexec

\connect bd_ferrovelho

CREATE SCHEMA IF NOT EXISTS dbo;
SET search_path TO dbo, public;

CREATE TABLE IF NOT EXISTS tb_cliente (
  id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpf_cliente VARCHAR(20),
  nome_cliente VARCHAR(100) NOT NULL,
  tel_cliente VARCHAR(11)
);

CREATE TABLE IF NOT EXISTS tb_tipousuario (
  id_tipousuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  desc_tipousuario VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_usuario (
  id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_usuario VARCHAR(50) NOT NULL,
  senha_usuario VARCHAR(50),
  permi_usuario INTEGER NOT NULL,
  ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS tb_produtos (
  id_prod INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  desc_prod VARCHAR(100),
  val_prod NUMERIC(18,2),
  usuario INTEGER
);

CREATE TABLE IF NOT EXISTS tb_compra (
  id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_compra TIMESTAMP NOT NULL,
  valor_nota NUMERIC(18,2),
  usuario INTEGER,
  desconto_compra NUMERIC(18,2),
  subtot_compra NUMERIC(18,2),
  id_cliente INTEGER,
  excluido BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE tb_compra
  ADD COLUMN IF NOT EXISTS excluido BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE tb_compra
SET excluido = FALSE
WHERE excluido IS NULL;

ALTER TABLE tb_compra
  ALTER COLUMN excluido SET DEFAULT FALSE,
  ALTER COLUMN excluido SET NOT NULL;

CREATE TABLE IF NOT EXISTS tb_venda (
  id_venda INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_venda TIMESTAMP NOT NULL,
  valor_nota NUMERIC(18,2) NOT NULL,
  usuario INTEGER,
  excluido BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE tb_venda
  ADD COLUMN IF NOT EXISTS excluido BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE tb_venda
SET excluido = FALSE
WHERE excluido IS NULL;

ALTER TABLE tb_venda
  ALTER COLUMN excluido SET DEFAULT FALSE,
  ALTER COLUMN excluido SET NOT NULL;

CREATE TABLE IF NOT EXISTS tb_itemc (
  id_item INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_prod INTEGER NOT NULL,
  id_compra INTEGER NOT NULL,
  quant_item NUMERIC(18,3) NOT NULL,
  subtot_item NUMERIC(18,3) NOT NULL,
  valor_item NUMERIC(18,3) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_itemv (
  id_item INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_prod INTEGER,
  id_venda INTEGER,
  quant_item NUMERIC(18,3),
  subtot_item NUMERIC(18,2),
  valr_item NUMERIC(18,2)
);

CREATE TABLE IF NOT EXISTS tb_caixa (
  id_caixa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_caixa TIMESTAMP NOT NULL,
  valor_caixa NUMERIC(18,2) NOT NULL,
  usuario INTEGER NOT NULL,
  desc_caixa VARCHAR(100),
  id_cliente INTEGER
);

CREATE TABLE IF NOT EXISTS tb_acliente (
  id_acliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_acliente TIMESTAMP NOT NULL,
  valor_acliente NUMERIC(18,2) NOT NULL,
  usuario INTEGER NOT NULL,
  desc_acliente VARCHAR(100),
  id_cliente INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_impressora (
  id_impressora INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_impressora VARCHAR(100)
);

ALTER TABLE tb_usuario
  DROP CONSTRAINT IF EXISTS fk_tb_usuario_tb_tipousuario;
ALTER TABLE tb_usuario
  ADD CONSTRAINT fk_tb_usuario_tb_tipousuario
  FOREIGN KEY (permi_usuario) REFERENCES tb_tipousuario(id_tipousuario);

ALTER TABLE tb_venda
  DROP CONSTRAINT IF EXISTS fk_tb_venda_tb_usuario;
ALTER TABLE tb_venda
  ADD CONSTRAINT fk_tb_venda_tb_usuario
  FOREIGN KEY (usuario) REFERENCES tb_usuario(id_usuario);

ALTER TABLE tb_caixa
  DROP CONSTRAINT IF EXISTS fk_tb_caixa_tb_usuario;
ALTER TABLE tb_caixa
  ADD CONSTRAINT fk_tb_caixa_tb_usuario
  FOREIGN KEY (usuario) REFERENCES tb_usuario(id_usuario);

ALTER TABLE tb_caixa
  DROP CONSTRAINT IF EXISTS tb_caixa_tb_cliente_fk;
ALTER TABLE tb_caixa
  ADD CONSTRAINT tb_caixa_tb_cliente_fk
  FOREIGN KEY (id_cliente) REFERENCES tb_cliente(id_cliente);

ALTER TABLE tb_acliente
  DROP CONSTRAINT IF EXISTS fk_tb_acliente_tb_usuario;
ALTER TABLE tb_acliente
  ADD CONSTRAINT fk_tb_acliente_tb_usuario
  FOREIGN KEY (usuario) REFERENCES tb_usuario(id_usuario);

ALTER TABLE tb_acliente
  DROP CONSTRAINT IF EXISTS fk_tb_acliente_tb_cliente;
ALTER TABLE tb_acliente
  ADD CONSTRAINT fk_tb_acliente_tb_cliente
  FOREIGN KEY (id_cliente) REFERENCES tb_cliente(id_cliente);

ALTER TABLE tb_itemc
  DROP CONSTRAINT IF EXISTS fk_tb_itemc_tb_compra;
ALTER TABLE tb_itemc
  ADD CONSTRAINT fk_tb_itemc_tb_compra
  FOREIGN KEY (id_compra) REFERENCES tb_compra(id_compra);

ALTER TABLE tb_itemc
  DROP CONSTRAINT IF EXISTS fk_tb_itemc_tb_produtos;
ALTER TABLE tb_itemc
  ADD CONSTRAINT fk_tb_itemc_tb_produtos
  FOREIGN KEY (id_prod) REFERENCES tb_produtos(id_prod);

ALTER TABLE tb_itemv
  DROP CONSTRAINT IF EXISTS fk_tb_itemv_tb_produtos;
ALTER TABLE tb_itemv
  ADD CONSTRAINT fk_tb_itemv_tb_produtos
  FOREIGN KEY (id_prod) REFERENCES tb_produtos(id_prod);

ALTER TABLE tb_itemv
  DROP CONSTRAINT IF EXISTS fk_tb_itemv_tb_venda;
ALTER TABLE tb_itemv
  ADD CONSTRAINT fk_tb_itemv_tb_venda
  FOREIGN KEY (id_venda) REFERENCES tb_venda(id_venda);

CREATE OR REPLACE FUNCTION s_tb_estoque(
  data_inicial TIMESTAMP,
  data_final TIMESTAMP,
  p_id_prod INTEGER DEFAULT NULL
)
RETURNS TABLE (
  codigo INTEGER,
  descricao TEXT,
  inicio NUMERIC,
  entrada NUMERIC,
  saida NUMERIC,
  saldo NUMERIC
)
LANGUAGE sql
AS $$
WITH estoque AS (
  SELECT id_prod, SUM(inicio) AS inicio, 0::NUMERIC AS entrada, 0::NUMERIC AS saida
  FROM (
    SELECT tic.id_prod, SUM(tic.quant_item) AS inicio
    FROM tb_itemc tic
    INNER JOIN tb_compra tc ON tc.id_compra = tic.id_compra
    WHERE tc.data_compra < data_inicial
      AND COALESCE(tc.excluido, FALSE) = FALSE
    GROUP BY tic.id_prod

    UNION ALL

    SELECT tiv.id_prod, -SUM(tiv.quant_item) AS inicio
    FROM tb_itemv tiv
    INNER JOIN tb_venda tv ON tv.id_venda = tiv.id_venda
    WHERE tv.data_venda < data_inicial
      AND COALESCE(tv.excluido, FALSE) = FALSE
    GROUP BY tiv.id_prod
  ) x
  GROUP BY id_prod

  UNION ALL

  SELECT tic.id_prod, 0::NUMERIC AS inicio, SUM(tic.quant_item) AS entrada, 0::NUMERIC AS saida
  FROM tb_itemc tic
  INNER JOIN tb_compra tc ON tc.id_compra = tic.id_compra
  WHERE tc.data_compra BETWEEN data_inicial AND data_final
    AND COALESCE(tc.excluido, FALSE) = FALSE
  GROUP BY tic.id_prod

  UNION ALL

  SELECT tiv.id_prod, 0::NUMERIC AS inicio, 0::NUMERIC AS entrada, SUM(tiv.quant_item) AS saida
  FROM tb_itemv tiv
  INNER JOIN tb_venda tv ON tv.id_venda = tiv.id_venda
  WHERE tv.data_venda BETWEEN data_inicial AND data_final
    AND COALESCE(tv.excluido, FALSE) = FALSE
  GROUP BY tiv.id_prod
)
SELECT
  e.id_prod AS codigo,
  UPPER(tp.desc_prod)::TEXT AS descricao,
  COALESCE(SUM(e.inicio), 0) AS inicio,
  COALESCE(SUM(e.entrada), 0) AS entrada,
  COALESCE(SUM(e.saida), 0) AS saida,
  COALESCE(SUM(e.inicio), 0) + COALESCE(SUM(e.entrada), 0) - COALESCE(SUM(e.saida), 0) AS saldo
FROM estoque e
INNER JOIN tb_produtos tp ON tp.id_prod = e.id_prod
WHERE p_id_prod IS NULL OR e.id_prod = p_id_prod
GROUP BY tp.desc_prod, e.id_prod
ORDER BY e.id_prod;
$$;

