#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerroVelhoDAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_ferroVelho")]
	public partial class FerroVelhoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_impressora(tb_impressora instance);
    partial void Updatetb_impressora(tb_impressora instance);
    partial void Deletetb_impressora(tb_impressora instance);
    partial void Inserttb_itemc(tb_itemc instance);
    partial void Updatetb_itemc(tb_itemc instance);
    partial void Deletetb_itemc(tb_itemc instance);
    partial void Inserttb_itemv(tb_itemv instance);
    partial void Updatetb_itemv(tb_itemv instance);
    partial void Deletetb_itemv(tb_itemv instance);
    partial void Inserttb_usuario(tb_usuario instance);
    partial void Updatetb_usuario(tb_usuario instance);
    partial void Deletetb_usuario(tb_usuario instance);
    partial void Inserttb_tipoUsuario(tb_tipoUsuario instance);
    partial void Updatetb_tipoUsuario(tb_tipoUsuario instance);
    partial void Deletetb_tipoUsuario(tb_tipoUsuario instance);
    partial void Inserttb_produtos(tb_produtos instance);
    partial void Updatetb_produtos(tb_produtos instance);
    partial void Deletetb_produtos(tb_produtos instance);
    partial void Inserttb_venda(tb_venda instance);
    partial void Updatetb_venda(tb_venda instance);
    partial void Deletetb_venda(tb_venda instance);
    partial void Inserttb_compra(tb_compra instance);
    partial void Updatetb_compra(tb_compra instance);
    partial void Deletetb_compra(tb_compra instance);
    partial void Inserttb_cliente(tb_cliente instance);
    partial void Updatetb_cliente(tb_cliente instance);
    partial void Deletetb_cliente(tb_cliente instance);
    partial void Inserttb_caixa(tb_caixa instance);
    partial void Updatetb_caixa(tb_caixa instance);
    partial void Deletetb_caixa(tb_caixa instance);
    partial void Inserttb_aCliente(tb_aCliente instance);
    partial void Updatetb_aCliente(tb_aCliente instance);
    partial void Deletetb_aCliente(tb_aCliente instance);
    #endregion
		
		public FerroVelhoDataContext() : 
				base(global::FerroVelhoDAO.Properties.Settings.Default.bd_ferroVelhoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public FerroVelhoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FerroVelhoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FerroVelhoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FerroVelhoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_impressora> tb_impressora
		{
			get
			{
				return this.GetTable<tb_impressora>();
			}
		}
		
		public System.Data.Linq.Table<tb_itemc> tb_itemc
		{
			get
			{
				return this.GetTable<tb_itemc>();
			}
		}
		
		public System.Data.Linq.Table<tb_itemv> tb_itemv
		{
			get
			{
				return this.GetTable<tb_itemv>();
			}
		}
		
		public System.Data.Linq.Table<tb_usuario> tb_usuario
		{
			get
			{
				return this.GetTable<tb_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tb_tipoUsuario> tb_tipoUsuario
		{
			get
			{
				return this.GetTable<tb_tipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tb_produtos> tb_produtos
		{
			get
			{
				return this.GetTable<tb_produtos>();
			}
		}
		
		public System.Data.Linq.Table<tb_venda> tb_venda
		{
			get
			{
				return this.GetTable<tb_venda>();
			}
		}
		
		public System.Data.Linq.Table<tb_compra> tb_compra
		{
			get
			{
				return this.GetTable<tb_compra>();
			}
		}
		
		public System.Data.Linq.Table<tb_cliente> tb_cliente
		{
			get
			{
				return this.GetTable<tb_cliente>();
			}
		}
		
		public System.Data.Linq.Table<tb_caixa> tb_caixa
		{
			get
			{
				return this.GetTable<tb_caixa>();
			}
		}
		
		public System.Data.Linq.Table<tb_aCliente> tb_aCliente
		{
			get
			{
				return this.GetTable<tb_aCliente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_impressora")]
	public partial class tb_impressora : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_impressora;
		
		private string _nome_impressora;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_impressoraChanging(int value);
    partial void Onid_impressoraChanged();
    partial void Onnome_impressoraChanging(string value);
    partial void Onnome_impressoraChanged();
    #endregion
		
		public tb_impressora()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_impressora", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_impressora
		{
			get
			{
				return this._id_impressora;
			}
			set
			{
				if ((this._id_impressora != value))
				{
					this.Onid_impressoraChanging(value);
					this.SendPropertyChanging();
					this._id_impressora = value;
					this.SendPropertyChanged("id_impressora");
					this.Onid_impressoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_impressora", DbType="VarChar(100)")]
		public string nome_impressora
		{
			get
			{
				return this._nome_impressora;
			}
			set
			{
				if ((this._nome_impressora != value))
				{
					this.Onnome_impressoraChanging(value);
					this.SendPropertyChanging();
					this._nome_impressora = value;
					this.SendPropertyChanged("nome_impressora");
					this.Onnome_impressoraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itemc")]
	public partial class tb_itemc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_item;
		
		private int _id_prod;
		
		private int _id_compra;
		
		private decimal _quant_item;
		
		private decimal _subTot_item;
		
		private decimal _valor_item;
		
		private EntityRef<tb_produtos> _tb_produtos;
		
		private EntityRef<tb_compra> _tb_compra;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    partial void Onid_prodChanging(int value);
    partial void Onid_prodChanged();
    partial void Onid_compraChanging(int value);
    partial void Onid_compraChanged();
    partial void Onquant_itemChanging(decimal value);
    partial void Onquant_itemChanged();
    partial void OnsubTot_itemChanging(decimal value);
    partial void OnsubTot_itemChanged();
    partial void Onvalor_itemChanging(decimal value);
    partial void Onvalor_itemChanged();
    #endregion
		
		public tb_itemc()
		{
			this._tb_produtos = default(EntityRef<tb_produtos>);
			this._tb_compra = default(EntityRef<tb_compra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prod", DbType="Int NOT NULL")]
		public int id_prod
		{
			get
			{
				return this._id_prod;
			}
			set
			{
				if ((this._id_prod != value))
				{
					if (this._tb_produtos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_prodChanging(value);
					this.SendPropertyChanging();
					this._id_prod = value;
					this.SendPropertyChanged("id_prod");
					this.Onid_prodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", DbType="Int NOT NULL")]
		public int id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					if (this._tb_compra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_compraChanging(value);
					this.SendPropertyChanging();
					this._id_compra = value;
					this.SendPropertyChanged("id_compra");
					this.Onid_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quant_item", DbType="Decimal(18,3) NOT NULL")]
		public decimal quant_item
		{
			get
			{
				return this._quant_item;
			}
			set
			{
				if ((this._quant_item != value))
				{
					this.Onquant_itemChanging(value);
					this.SendPropertyChanging();
					this._quant_item = value;
					this.SendPropertyChanged("quant_item");
					this.Onquant_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subTot_item", DbType="Decimal(18,3) NOT NULL")]
		public decimal subTot_item
		{
			get
			{
				return this._subTot_item;
			}
			set
			{
				if ((this._subTot_item != value))
				{
					this.OnsubTot_itemChanging(value);
					this.SendPropertyChanging();
					this._subTot_item = value;
					this.SendPropertyChanged("subTot_item");
					this.OnsubTot_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_item", DbType="Decimal(18,3) NOT NULL")]
		public decimal valor_item
		{
			get
			{
				return this._valor_item;
			}
			set
			{
				if ((this._valor_item != value))
				{
					this.Onvalor_itemChanging(value);
					this.SendPropertyChanging();
					this._valor_item = value;
					this.SendPropertyChanged("valor_item");
					this.Onvalor_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produtos_tb_itemc", Storage="_tb_produtos", ThisKey="id_prod", OtherKey="id_prod", IsForeignKey=true)]
		public tb_produtos tb_produtos
		{
			get
			{
				return this._tb_produtos.Entity;
			}
			set
			{
				tb_produtos previousValue = this._tb_produtos.Entity;
				if (((previousValue != value) 
							|| (this._tb_produtos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_produtos.Entity = null;
						previousValue.tb_itemc.Remove(this);
					}
					this._tb_produtos.Entity = value;
					if ((value != null))
					{
						value.tb_itemc.Add(this);
						this._id_prod = value.id_prod;
					}
					else
					{
						this._id_prod = default(int);
					}
					this.SendPropertyChanged("tb_produtos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_compra_tb_itemc", Storage="_tb_compra", ThisKey="id_compra", OtherKey="id_compra", IsForeignKey=true)]
		public tb_compra tb_compra
		{
			get
			{
				return this._tb_compra.Entity;
			}
			set
			{
				tb_compra previousValue = this._tb_compra.Entity;
				if (((previousValue != value) 
							|| (this._tb_compra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_compra.Entity = null;
						previousValue.tb_itemc.Remove(this);
					}
					this._tb_compra.Entity = value;
					if ((value != null))
					{
						value.tb_itemc.Add(this);
						this._id_compra = value.id_compra;
					}
					else
					{
						this._id_compra = default(int);
					}
					this.SendPropertyChanged("tb_compra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itemv")]
	public partial class tb_itemv : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_item;
		
		private System.Nullable<int> _id_prod;
		
		private System.Nullable<int> _id_venda;
		
		private System.Nullable<decimal> _quant_item;
		
		private System.Nullable<decimal> _subTot_item;
		
		private System.Nullable<decimal> _valr_item;
		
		private EntityRef<tb_produtos> _tb_produtos;
		
		private EntityRef<tb_venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    partial void Onid_prodChanging(System.Nullable<int> value);
    partial void Onid_prodChanged();
    partial void Onid_vendaChanging(System.Nullable<int> value);
    partial void Onid_vendaChanged();
    partial void Onquant_itemChanging(System.Nullable<decimal> value);
    partial void Onquant_itemChanged();
    partial void OnsubTot_itemChanging(System.Nullable<decimal> value);
    partial void OnsubTot_itemChanged();
    partial void Onvalr_itemChanging(System.Nullable<decimal> value);
    partial void Onvalr_itemChanged();
    #endregion
		
		public tb_itemv()
		{
			this._tb_produtos = default(EntityRef<tb_produtos>);
			this._tb_venda = default(EntityRef<tb_venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prod", DbType="Int")]
		public System.Nullable<int> id_prod
		{
			get
			{
				return this._id_prod;
			}
			set
			{
				if ((this._id_prod != value))
				{
					if (this._tb_produtos.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_prodChanging(value);
					this.SendPropertyChanging();
					this._id_prod = value;
					this.SendPropertyChanged("id_prod");
					this.Onid_prodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int")]
		public System.Nullable<int> id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._tb_venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quant_item", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> quant_item
		{
			get
			{
				return this._quant_item;
			}
			set
			{
				if ((this._quant_item != value))
				{
					this.Onquant_itemChanging(value);
					this.SendPropertyChanging();
					this._quant_item = value;
					this.SendPropertyChanged("quant_item");
					this.Onquant_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subTot_item", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> subTot_item
		{
			get
			{
				return this._subTot_item;
			}
			set
			{
				if ((this._subTot_item != value))
				{
					this.OnsubTot_itemChanging(value);
					this.SendPropertyChanging();
					this._subTot_item = value;
					this.SendPropertyChanged("subTot_item");
					this.OnsubTot_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valr_item", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valr_item
		{
			get
			{
				return this._valr_item;
			}
			set
			{
				if ((this._valr_item != value))
				{
					this.Onvalr_itemChanging(value);
					this.SendPropertyChanging();
					this._valr_item = value;
					this.SendPropertyChanged("valr_item");
					this.Onvalr_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produtos_tb_itemv", Storage="_tb_produtos", ThisKey="id_prod", OtherKey="id_prod", IsForeignKey=true)]
		public tb_produtos tb_produtos
		{
			get
			{
				return this._tb_produtos.Entity;
			}
			set
			{
				tb_produtos previousValue = this._tb_produtos.Entity;
				if (((previousValue != value) 
							|| (this._tb_produtos.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_produtos.Entity = null;
						previousValue.tb_itemv.Remove(this);
					}
					this._tb_produtos.Entity = value;
					if ((value != null))
					{
						value.tb_itemv.Add(this);
						this._id_prod = value.id_prod;
					}
					else
					{
						this._id_prod = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_produtos");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itemv", Storage="_tb_venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true)]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_itemv.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_itemv.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class tb_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nome_usuario;
		
		private string _senha_usuario;
		
		private int _permi_usuario;
		
		private EntitySet<tb_venda> _tb_venda;
		
		private EntitySet<tb_compra> _tb_compra;
		
		private EntitySet<tb_caixa> _tb_caixa;
		
		private EntitySet<tb_aCliente> _tb_aCliente;
		
		private EntityRef<tb_tipoUsuario> _tb_tipoUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onnome_usuarioChanging(string value);
    partial void Onnome_usuarioChanged();
    partial void Onsenha_usuarioChanging(string value);
    partial void Onsenha_usuarioChanged();
    partial void Onpermi_usuarioChanging(int value);
    partial void Onpermi_usuarioChanged();
    #endregion
		
		public tb_usuario()
		{
			this._tb_venda = new EntitySet<tb_venda>(new Action<tb_venda>(this.attach_tb_venda), new Action<tb_venda>(this.detach_tb_venda));
			this._tb_compra = new EntitySet<tb_compra>(new Action<tb_compra>(this.attach_tb_compra), new Action<tb_compra>(this.detach_tb_compra));
			this._tb_caixa = new EntitySet<tb_caixa>(new Action<tb_caixa>(this.attach_tb_caixa), new Action<tb_caixa>(this.detach_tb_caixa));
			this._tb_aCliente = new EntitySet<tb_aCliente>(new Action<tb_aCliente>(this.attach_tb_aCliente), new Action<tb_aCliente>(this.detach_tb_aCliente));
			this._tb_tipoUsuario = default(EntityRef<tb_tipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome_usuario
		{
			get
			{
				return this._nome_usuario;
			}
			set
			{
				if ((this._nome_usuario != value))
				{
					this.Onnome_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nome_usuario = value;
					this.SendPropertyChanged("nome_usuario");
					this.Onnome_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha_usuario", DbType="VarChar(50)")]
		public string senha_usuario
		{
			get
			{
				return this._senha_usuario;
			}
			set
			{
				if ((this._senha_usuario != value))
				{
					this.Onsenha_usuarioChanging(value);
					this.SendPropertyChanging();
					this._senha_usuario = value;
					this.SendPropertyChanged("senha_usuario");
					this.Onsenha_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_permi_usuario", DbType="Int NOT NULL")]
		public int permi_usuario
		{
			get
			{
				return this._permi_usuario;
			}
			set
			{
				if ((this._permi_usuario != value))
				{
					if (this._tb_tipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpermi_usuarioChanging(value);
					this.SendPropertyChanging();
					this._permi_usuario = value;
					this.SendPropertyChanged("permi_usuario");
					this.Onpermi_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_venda", Storage="_tb_venda", ThisKey="id_usuario", OtherKey="usuario")]
		public EntitySet<tb_venda> tb_venda
		{
			get
			{
				return this._tb_venda;
			}
			set
			{
				this._tb_venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_compra", Storage="_tb_compra", ThisKey="id_usuario", OtherKey="usuario")]
		public EntitySet<tb_compra> tb_compra
		{
			get
			{
				return this._tb_compra;
			}
			set
			{
				this._tb_compra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_caixa", Storage="_tb_caixa", ThisKey="id_usuario", OtherKey="usuario")]
		public EntitySet<tb_caixa> tb_caixa
		{
			get
			{
				return this._tb_caixa;
			}
			set
			{
				this._tb_caixa.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_aCliente", Storage="_tb_aCliente", ThisKey="id_usuario", OtherKey="usuario")]
		public EntitySet<tb_aCliente> tb_aCliente
		{
			get
			{
				return this._tb_aCliente;
			}
			set
			{
				this._tb_aCliente.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_tipoUsuario_tb_usuario", Storage="_tb_tipoUsuario", ThisKey="permi_usuario", OtherKey="id_tipoUsuario", IsForeignKey=true)]
		public tb_tipoUsuario tb_tipoUsuario
		{
			get
			{
				return this._tb_tipoUsuario.Entity;
			}
			set
			{
				tb_tipoUsuario previousValue = this._tb_tipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_tipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_tipoUsuario.Entity = null;
						previousValue.tb_usuario.Remove(this);
					}
					this._tb_tipoUsuario.Entity = value;
					if ((value != null))
					{
						value.tb_usuario.Add(this);
						this._permi_usuario = value.id_tipoUsuario;
					}
					else
					{
						this._permi_usuario = default(int);
					}
					this.SendPropertyChanged("tb_tipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_venda(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = this;
		}
		
		private void detach_tb_venda(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = null;
		}
		
		private void attach_tb_compra(tb_compra entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = this;
		}
		
		private void detach_tb_compra(tb_compra entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = null;
		}
		
		private void attach_tb_caixa(tb_caixa entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = this;
		}
		
		private void detach_tb_caixa(tb_caixa entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = null;
		}
		
		private void attach_tb_aCliente(tb_aCliente entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = this;
		}
		
		private void detach_tb_aCliente(tb_aCliente entity)
		{
			this.SendPropertyChanging();
			entity.tb_usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_tipoUsuario")]
	public partial class tb_tipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipoUsuario;
		
		private string _desc_tipoUsuario;
		
		private EntitySet<tb_usuario> _tb_usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipoUsuarioChanging(int value);
    partial void Onid_tipoUsuarioChanged();
    partial void Ondesc_tipoUsuarioChanging(string value);
    partial void Ondesc_tipoUsuarioChanged();
    #endregion
		
		public tb_tipoUsuario()
		{
			this._tb_usuario = new EntitySet<tb_usuario>(new Action<tb_usuario>(this.attach_tb_usuario), new Action<tb_usuario>(this.detach_tb_usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipoUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipoUsuario
		{
			get
			{
				return this._id_tipoUsuario;
			}
			set
			{
				if ((this._id_tipoUsuario != value))
				{
					this.Onid_tipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._id_tipoUsuario = value;
					this.SendPropertyChanged("id_tipoUsuario");
					this.Onid_tipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_tipoUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string desc_tipoUsuario
		{
			get
			{
				return this._desc_tipoUsuario;
			}
			set
			{
				if ((this._desc_tipoUsuario != value))
				{
					this.Ondesc_tipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._desc_tipoUsuario = value;
					this.SendPropertyChanged("desc_tipoUsuario");
					this.Ondesc_tipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_tipoUsuario_tb_usuario", Storage="_tb_usuario", ThisKey="id_tipoUsuario", OtherKey="permi_usuario")]
		public EntitySet<tb_usuario> tb_usuario
		{
			get
			{
				return this._tb_usuario;
			}
			set
			{
				this._tb_usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_usuario(tb_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tb_tipoUsuario = this;
		}
		
		private void detach_tb_usuario(tb_usuario entity)
		{
			this.SendPropertyChanging();
			entity.tb_tipoUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produtos")]
	public partial class tb_produtos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_prod;
		
		private string _desc_prod;
		
		private System.Nullable<decimal> _val_prod;
		
		private System.Nullable<int> _usuario;
		
		private EntitySet<tb_itemc> _tb_itemc;
		
		private EntitySet<tb_itemv> _tb_itemv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_prodChanging(int value);
    partial void Onid_prodChanged();
    partial void Ondesc_prodChanging(string value);
    partial void Ondesc_prodChanged();
    partial void Onval_prodChanging(System.Nullable<decimal> value);
    partial void Onval_prodChanged();
    partial void OnusuarioChanging(System.Nullable<int> value);
    partial void OnusuarioChanged();
    #endregion
		
		public tb_produtos()
		{
			this._tb_itemc = new EntitySet<tb_itemc>(new Action<tb_itemc>(this.attach_tb_itemc), new Action<tb_itemc>(this.detach_tb_itemc));
			this._tb_itemv = new EntitySet<tb_itemv>(new Action<tb_itemv>(this.attach_tb_itemv), new Action<tb_itemv>(this.detach_tb_itemv));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_prod
		{
			get
			{
				return this._id_prod;
			}
			set
			{
				if ((this._id_prod != value))
				{
					this.Onid_prodChanging(value);
					this.SendPropertyChanging();
					this._id_prod = value;
					this.SendPropertyChanged("id_prod");
					this.Onid_prodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_prod", DbType="VarChar(100)")]
		public string desc_prod
		{
			get
			{
				return this._desc_prod;
			}
			set
			{
				if ((this._desc_prod != value))
				{
					this.Ondesc_prodChanging(value);
					this.SendPropertyChanging();
					this._desc_prod = value;
					this.SendPropertyChanged("desc_prod");
					this.Ondesc_prodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_val_prod", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> val_prod
		{
			get
			{
				return this._val_prod;
			}
			set
			{
				if ((this._val_prod != value))
				{
					this.Onval_prodChanging(value);
					this.SendPropertyChanging();
					this._val_prod = value;
					this.SendPropertyChanged("val_prod");
					this.Onval_prodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Int")]
		public System.Nullable<int> usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produtos_tb_itemc", Storage="_tb_itemc", ThisKey="id_prod", OtherKey="id_prod")]
		public EntitySet<tb_itemc> tb_itemc
		{
			get
			{
				return this._tb_itemc;
			}
			set
			{
				this._tb_itemc.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produtos_tb_itemv", Storage="_tb_itemv", ThisKey="id_prod", OtherKey="id_prod")]
		public EntitySet<tb_itemv> tb_itemv
		{
			get
			{
				return this._tb_itemv;
			}
			set
			{
				this._tb_itemv.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itemc(tb_itemc entity)
		{
			this.SendPropertyChanging();
			entity.tb_produtos = this;
		}
		
		private void detach_tb_itemc(tb_itemc entity)
		{
			this.SendPropertyChanging();
			entity.tb_produtos = null;
		}
		
		private void attach_tb_itemv(tb_itemv entity)
		{
			this.SendPropertyChanging();
			entity.tb_produtos = this;
		}
		
		private void detach_tb_itemv(tb_itemv entity)
		{
			this.SendPropertyChanging();
			entity.tb_produtos = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class tb_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venda;
		
		private System.DateTime _data_venda;
		
		private decimal _valor_nota;
		
		private System.Nullable<int> _usuario;
		
		private EntitySet<tb_itemv> _tb_itemv;
		
		private EntityRef<tb_usuario> _tb_usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void Ondata_vendaChanging(System.DateTime value);
    partial void Ondata_vendaChanged();
    partial void Onvalor_notaChanging(decimal value);
    partial void Onvalor_notaChanged();
    partial void OnusuarioChanging(System.Nullable<int> value);
    partial void OnusuarioChanged();
    #endregion
		
		public tb_venda()
		{
			this._tb_itemv = new EntitySet<tb_itemv>(new Action<tb_itemv>(this.attach_tb_itemv), new Action<tb_itemv>(this.detach_tb_itemv));
			this._tb_usuario = default(EntityRef<tb_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_venda", DbType="DateTime NOT NULL")]
		public System.DateTime data_venda
		{
			get
			{
				return this._data_venda;
			}
			set
			{
				if ((this._data_venda != value))
				{
					this.Ondata_vendaChanging(value);
					this.SendPropertyChanging();
					this._data_venda = value;
					this.SendPropertyChanged("data_venda");
					this.Ondata_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_nota", DbType="Decimal(18,2) NOT NULL")]
		public decimal valor_nota
		{
			get
			{
				return this._valor_nota;
			}
			set
			{
				if ((this._valor_nota != value))
				{
					this.Onvalor_notaChanging(value);
					this.SendPropertyChanging();
					this._valor_nota = value;
					this.SendPropertyChanged("valor_nota");
					this.Onvalor_notaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Int")]
		public System.Nullable<int> usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					if (this._tb_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itemv", Storage="_tb_itemv", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<tb_itemv> tb_itemv
		{
			get
			{
				return this._tb_itemv;
			}
			set
			{
				this._tb_itemv.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_venda", Storage="_tb_usuario", ThisKey="usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tb_usuario tb_usuario
		{
			get
			{
				return this._tb_usuario.Entity;
			}
			set
			{
				tb_usuario previousValue = this._tb_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_usuario.Entity = null;
						previousValue.tb_venda.Remove(this);
					}
					this._tb_usuario.Entity = value;
					if ((value != null))
					{
						value.tb_venda.Add(this);
						this._usuario = value.id_usuario;
					}
					else
					{
						this._usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itemv(tb_itemv entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_itemv(tb_itemv entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_compra")]
	public partial class tb_compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_compra;
		
		private System.DateTime _data_compra;
		
		private decimal _desconto_compra;
		
		private decimal _subtot_compra;
		
		private decimal _valor_nota;
		
		private System.Nullable<int> _id_cliente;
		
		private int _usuario;
		
		private EntitySet<tb_itemc> _tb_itemc;
		
		private EntityRef<tb_usuario> _tb_usuario;
		
		private EntityRef<tb_cliente> _tb_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_compraChanging(int value);
    partial void Onid_compraChanged();
    partial void Ondata_compraChanging(System.DateTime value);
    partial void Ondata_compraChanged();
    partial void Ondesconto_compraChanging(decimal value);
    partial void Ondesconto_compraChanged();
    partial void Onsubtot_compraChanging(decimal value);
    partial void Onsubtot_compraChanged();
    partial void Onvalor_notaChanging(decimal value);
    partial void Onvalor_notaChanged();
    partial void Onid_clienteChanging(System.Nullable<int> value);
    partial void Onid_clienteChanged();
    partial void OnusuarioChanging(int value);
    partial void OnusuarioChanged();
    #endregion
		
		public tb_compra()
		{
			this._tb_itemc = new EntitySet<tb_itemc>(new Action<tb_itemc>(this.attach_tb_itemc), new Action<tb_itemc>(this.detach_tb_itemc));
			this._tb_usuario = default(EntityRef<tb_usuario>);
			this._tb_cliente = default(EntityRef<tb_cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_compra", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_compra
		{
			get
			{
				return this._id_compra;
			}
			set
			{
				if ((this._id_compra != value))
				{
					this.Onid_compraChanging(value);
					this.SendPropertyChanging();
					this._id_compra = value;
					this.SendPropertyChanged("id_compra");
					this.Onid_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_compra", DbType="DateTime NOT NULL")]
		public System.DateTime data_compra
		{
			get
			{
				return this._data_compra;
			}
			set
			{
				if ((this._data_compra != value))
				{
					this.Ondata_compraChanging(value);
					this.SendPropertyChanging();
					this._data_compra = value;
					this.SendPropertyChanged("data_compra");
					this.Ondata_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desconto_compra", DbType="Decimal(18,2) NOT NULL")]
		public decimal desconto_compra
		{
			get
			{
				return this._desconto_compra;
			}
			set
			{
				if ((this._desconto_compra != value))
				{
					this.Ondesconto_compraChanging(value);
					this.SendPropertyChanging();
					this._desconto_compra = value;
					this.SendPropertyChanged("desconto_compra");
					this.Ondesconto_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtot_compra", DbType="Decimal(18,2) NOT NULL")]
		public decimal subtot_compra
		{
			get
			{
				return this._subtot_compra;
			}
			set
			{
				if ((this._subtot_compra != value))
				{
					this.Onsubtot_compraChanging(value);
					this.SendPropertyChanging();
					this._subtot_compra = value;
					this.SendPropertyChanged("subtot_compra");
					this.Onsubtot_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_nota", DbType="Decimal(18,2) NOT NULL")]
		public decimal valor_nota
		{
			get
			{
				return this._valor_nota;
			}
			set
			{
				if ((this._valor_nota != value))
				{
					this.Onvalor_notaChanging(value);
					this.SendPropertyChanging();
					this._valor_nota = value;
					this.SendPropertyChanged("valor_nota");
					this.Onvalor_notaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._tb_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Int NOT NULL")]
		public int usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					if (this._tb_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_compra_tb_itemc", Storage="_tb_itemc", ThisKey="id_compra", OtherKey="id_compra")]
		public EntitySet<tb_itemc> tb_itemc
		{
			get
			{
				return this._tb_itemc;
			}
			set
			{
				this._tb_itemc.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_compra", Storage="_tb_usuario", ThisKey="usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tb_usuario tb_usuario
		{
			get
			{
				return this._tb_usuario.Entity;
			}
			set
			{
				tb_usuario previousValue = this._tb_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_usuario.Entity = null;
						previousValue.tb_compra.Remove(this);
					}
					this._tb_usuario.Entity = value;
					if ((value != null))
					{
						value.tb_compra.Add(this);
						this._usuario = value.id_usuario;
					}
					else
					{
						this._usuario = default(int);
					}
					this.SendPropertyChanged("tb_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_compra", Storage="_tb_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public tb_cliente tb_cliente
		{
			get
			{
				return this._tb_cliente.Entity;
			}
			set
			{
				tb_cliente previousValue = this._tb_cliente.Entity;
				if (((previousValue != value) 
							|| (this._tb_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_cliente.Entity = null;
						previousValue.tb_compra.Remove(this);
					}
					this._tb_cliente.Entity = value;
					if ((value != null))
					{
						value.tb_compra.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itemc(tb_itemc entity)
		{
			this.SendPropertyChanging();
			entity.tb_compra = this;
		}
		
		private void detach_tb_itemc(tb_itemc entity)
		{
			this.SendPropertyChanging();
			entity.tb_compra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_cliente")]
	public partial class tb_cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _cpf_cliente;
		
		private string _nome_cliente;
		
		private string _tel_cliente;
		
		private decimal _Saldo;
		
		private EntitySet<tb_compra> _tb_compra;
		
		private EntitySet<tb_caixa> _tb_caixa;
		
		private EntitySet<tb_aCliente> _tb_aCliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Oncpf_clienteChanging(string value);
    partial void Oncpf_clienteChanged();
    partial void Onnome_clienteChanging(string value);
    partial void Onnome_clienteChanged();
    partial void Ontel_clienteChanging(string value);
    partial void Ontel_clienteChanged();
    partial void OnSaldoChanging(decimal value);
    partial void OnSaldoChanged();
    #endregion
		
		public tb_cliente()
		{
			this._tb_compra = new EntitySet<tb_compra>(new Action<tb_compra>(this.attach_tb_compra), new Action<tb_compra>(this.detach_tb_compra));
			this._tb_caixa = new EntitySet<tb_caixa>(new Action<tb_caixa>(this.attach_tb_caixa), new Action<tb_caixa>(this.detach_tb_caixa));
			this._tb_aCliente = new EntitySet<tb_aCliente>(new Action<tb_aCliente>(this.attach_tb_aCliente), new Action<tb_aCliente>(this.detach_tb_aCliente));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf_cliente", DbType="VarChar(20)")]
		public string cpf_cliente
		{
			get
			{
				return this._cpf_cliente;
			}
			set
			{
				if ((this._cpf_cliente != value))
				{
					this.Oncpf_clienteChanging(value);
					this.SendPropertyChanging();
					this._cpf_cliente = value;
					this.SendPropertyChanged("cpf_cliente");
					this.Oncpf_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome_cliente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nome_cliente
		{
			get
			{
				return this._nome_cliente;
			}
			set
			{
				if ((this._nome_cliente != value))
				{
					this.Onnome_clienteChanging(value);
					this.SendPropertyChanging();
					this._nome_cliente = value;
					this.SendPropertyChanged("nome_cliente");
					this.Onnome_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_cliente", DbType="VarChar(15)")]
		public string tel_cliente
		{
			get
			{
				return this._tel_cliente;
			}
			set
			{
				if ((this._tel_cliente != value))
				{
					this.Ontel_clienteChanging(value);
					this.SendPropertyChanging();
					this._tel_cliente = value;
					this.SendPropertyChanged("tel_cliente");
					this.Ontel_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo")]
		public decimal Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_compra", Storage="_tb_compra", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<tb_compra> tb_compra
		{
			get
			{
				return this._tb_compra;
			}
			set
			{
				this._tb_compra.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_caixa", Storage="_tb_caixa", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<tb_caixa> tb_caixa
		{
			get
			{
				return this._tb_caixa;
			}
			set
			{
				this._tb_caixa.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_aCliente", Storage="_tb_aCliente", ThisKey="id_cliente", OtherKey="id_cliente")]
		public EntitySet<tb_aCliente> tb_aCliente
		{
			get
			{
				return this._tb_aCliente;
			}
			set
			{
				this._tb_aCliente.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_compra(tb_compra entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = this;
		}
		
		private void detach_tb_compra(tb_compra entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = null;
		}
		
		private void attach_tb_caixa(tb_caixa entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = this;
		}
		
		private void detach_tb_caixa(tb_caixa entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = null;
		}
		
		private void attach_tb_aCliente(tb_aCliente entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = this;
		}
		
		private void detach_tb_aCliente(tb_aCliente entity)
		{
			this.SendPropertyChanging();
			entity.tb_cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_caixa")]
	public partial class tb_caixa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_caixa;
		
		private System.DateTime _data_caixa;
		
		private decimal _valor_caixa;
		
		private System.Nullable<int> _usuario;
		
		private string _desc_caixa;
		
		private System.Nullable<int> _id_cliente;
		
		private EntityRef<tb_cliente> _tb_cliente;
		
		private EntityRef<tb_usuario> _tb_usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_caixaChanging(int value);
    partial void OnId_caixaChanged();
    partial void Ondata_caixaChanging(System.DateTime value);
    partial void Ondata_caixaChanged();
    partial void Onvalor_caixaChanging(decimal value);
    partial void Onvalor_caixaChanged();
    partial void OnusuarioChanging(System.Nullable<int> value);
    partial void OnusuarioChanged();
    partial void Ondesc_caixaChanging(string value);
    partial void Ondesc_caixaChanged();
    partial void Onid_clienteChanging(System.Nullable<int> value);
    partial void Onid_clienteChanged();
    #endregion
		
		public tb_caixa()
		{
			this._tb_cliente = default(EntityRef<tb_cliente>);
			this._tb_usuario = default(EntityRef<tb_usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_caixa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_caixa
		{
			get
			{
				return this._Id_caixa;
			}
			set
			{
				if ((this._Id_caixa != value))
				{
					this.OnId_caixaChanging(value);
					this.SendPropertyChanging();
					this._Id_caixa = value;
					this.SendPropertyChanged("Id_caixa");
					this.OnId_caixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_caixa", DbType="DateTime NOT NULL")]
		public System.DateTime data_caixa
		{
			get
			{
				return this._data_caixa;
			}
			set
			{
				if ((this._data_caixa != value))
				{
					this.Ondata_caixaChanging(value);
					this.SendPropertyChanging();
					this._data_caixa = value;
					this.SendPropertyChanged("data_caixa");
					this.Ondata_caixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_caixa", DbType="Decimal(18,2) NOT NULL")]
		public decimal valor_caixa
		{
			get
			{
				return this._valor_caixa;
			}
			set
			{
				if ((this._valor_caixa != value))
				{
					this.Onvalor_caixaChanging(value);
					this.SendPropertyChanging();
					this._valor_caixa = value;
					this.SendPropertyChanged("valor_caixa");
					this.Onvalor_caixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Int")]
		public System.Nullable<int> usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					if (this._tb_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_caixa", DbType="VarChar(100)")]
		public string desc_caixa
		{
			get
			{
				return this._desc_caixa;
			}
			set
			{
				if ((this._desc_caixa != value))
				{
					this.Ondesc_caixaChanging(value);
					this.SendPropertyChanging();
					this._desc_caixa = value;
					this.SendPropertyChanged("desc_caixa");
					this.Ondesc_caixaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int")]
		public System.Nullable<int> id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._tb_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_caixa", Storage="_tb_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public tb_cliente tb_cliente
		{
			get
			{
				return this._tb_cliente.Entity;
			}
			set
			{
				tb_cliente previousValue = this._tb_cliente.Entity;
				if (((previousValue != value) 
							|| (this._tb_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_cliente.Entity = null;
						previousValue.tb_caixa.Remove(this);
					}
					this._tb_cliente.Entity = value;
					if ((value != null))
					{
						value.tb_caixa.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_caixa", Storage="_tb_usuario", ThisKey="usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tb_usuario tb_usuario
		{
			get
			{
				return this._tb_usuario.Entity;
			}
			set
			{
				tb_usuario previousValue = this._tb_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_usuario.Entity = null;
						previousValue.tb_caixa.Remove(this);
					}
					this._tb_usuario.Entity = value;
					if ((value != null))
					{
						value.tb_caixa.Add(this);
						this._usuario = value.id_usuario;
					}
					else
					{
						this._usuario = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_aCliente")]
	public partial class tb_aCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_aCliente;
		
		private System.DateTime _data__aCliente;
		
		private decimal _valor_aCliente;
		
		private int _usuario;
		
		private string _desc_aCliente;
		
		private int _id_cliente;
		
		private EntityRef<tb_usuario> _tb_usuario;
		
		private EntityRef<tb_cliente> _tb_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_aClienteChanging(int value);
    partial void OnId_aClienteChanged();
    partial void Ondata__aClienteChanging(System.DateTime value);
    partial void Ondata__aClienteChanged();
    partial void Onvalor_aClienteChanging(decimal value);
    partial void Onvalor_aClienteChanged();
    partial void OnusuarioChanging(int value);
    partial void OnusuarioChanged();
    partial void Ondesc_aClienteChanging(string value);
    partial void Ondesc_aClienteChanged();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    #endregion
		
		public tb_aCliente()
		{
			this._tb_usuario = default(EntityRef<tb_usuario>);
			this._tb_cliente = default(EntityRef<tb_cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_aCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_aCliente
		{
			get
			{
				return this._Id_aCliente;
			}
			set
			{
				if ((this._Id_aCliente != value))
				{
					this.OnId_aClienteChanging(value);
					this.SendPropertyChanging();
					this._Id_aCliente = value;
					this.SendPropertyChanged("Id_aCliente");
					this.OnId_aClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data__aCliente", DbType="DateTime NOT NULL")]
		public System.DateTime data__aCliente
		{
			get
			{
				return this._data__aCliente;
			}
			set
			{
				if ((this._data__aCliente != value))
				{
					this.Ondata__aClienteChanging(value);
					this.SendPropertyChanging();
					this._data__aCliente = value;
					this.SendPropertyChanged("data__aCliente");
					this.Ondata__aClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_aCliente", DbType="Decimal(18,2) NOT NULL")]
		public decimal valor_aCliente
		{
			get
			{
				return this._valor_aCliente;
			}
			set
			{
				if ((this._valor_aCliente != value))
				{
					this.Onvalor_aClienteChanging(value);
					this.SendPropertyChanging();
					this._valor_aCliente = value;
					this.SendPropertyChanged("valor_aCliente");
					this.Onvalor_aClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Int NOT NULL")]
		public int usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					if (this._tb_usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desc_aCliente", DbType="VarChar(100)")]
		public string desc_aCliente
		{
			get
			{
				return this._desc_aCliente;
			}
			set
			{
				if ((this._desc_aCliente != value))
				{
					this.Ondesc_aClienteChanging(value);
					this.SendPropertyChanging();
					this._desc_aCliente = value;
					this.SendPropertyChanged("desc_aCliente");
					this.Ondesc_aClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", DbType="Int NOT NULL")]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					if (this._tb_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_usuario_tb_aCliente", Storage="_tb_usuario", ThisKey="usuario", OtherKey="id_usuario", IsForeignKey=true)]
		public tb_usuario tb_usuario
		{
			get
			{
				return this._tb_usuario.Entity;
			}
			set
			{
				tb_usuario previousValue = this._tb_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_usuario.Entity = null;
						previousValue.tb_aCliente.Remove(this);
					}
					this._tb_usuario.Entity = value;
					if ((value != null))
					{
						value.tb_aCliente.Add(this);
						this._usuario = value.id_usuario;
					}
					else
					{
						this._usuario = default(int);
					}
					this.SendPropertyChanged("tb_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_cliente_tb_aCliente", Storage="_tb_cliente", ThisKey="id_cliente", OtherKey="id_cliente", IsForeignKey=true)]
		public tb_cliente tb_cliente
		{
			get
			{
				return this._tb_cliente.Entity;
			}
			set
			{
				tb_cliente previousValue = this._tb_cliente.Entity;
				if (((previousValue != value) 
							|| (this._tb_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_cliente.Entity = null;
						previousValue.tb_aCliente.Remove(this);
					}
					this._tb_cliente.Entity = value;
					if ((value != null))
					{
						value.tb_aCliente.Add(this);
						this._id_cliente = value.id_cliente;
					}
					else
					{
						this._id_cliente = default(int);
					}
					this.SendPropertyChanged("tb_cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
