USE [master]
GO

/****** Object:  Database [bd_ferroVelho]    Script Date: 15/07/2021 17:08:00 ******/
CREATE DATABASE [bd_ferroVelho]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bd_ferrevelho', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\bd_ferrevelho.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'bd_ferrevelho_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\bd_ferrevelho_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [bd_ferroVelho] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bd_ferroVelho].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bd_ferroVelho] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET ARITHABORT OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bd_ferroVelho] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bd_ferroVelho] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bd_ferroVelho] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bd_ferroVelho] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bd_ferroVelho] SET  MULTI_USER 
GO

ALTER DATABASE [bd_ferroVelho] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bd_ferroVelho] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bd_ferroVelho] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bd_ferroVelho] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [bd_ferroVelho] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bd_ferroVelho] SET  READ_WRITE 
GO

